name: Weekly Python Script Execution

# Controls when the action will run
on:
  schedule:
    # Runs the job once a week, every Monday at 00:00 (UTC)
    - cron: '05 19 * * THU'

# Specifies the jobs that run as part of the workflow
jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x' # Specify the version of Python you want to use

    # Step 3: Install dependencies (if any)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # Step 4: Run your Python script
    - name: Run Python script
      run: python path/to/your_script.py
