name: Run Python Script On-Demand

# Allows the workflow to be triggered manually
on:
  workflow_dispatch:
    inputs:
        example_input:
          description: 'An example input parameter'
          required: true
          default: 'default_value'

# Specifies the jobs that run as part of the workflow
jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x' # Specify the version of Python you want to use

    # Step 3: Install dependencies (if any)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # Step 4: creating env file
    - name: Create .env file
      run: |
        echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env


    # Step 5: Run your Python script
    - name: Run Python script
      run: python chatgpt_api.py
